### ISSUE TITLE
File manipulation results in failure with "\\\\" separator

### ISSUE THREAD

**Issue by JerkyChew899** [aelfakih/Manage-Chia-Farm#1]
Running Windows 2019 Server with ~30 drives in a combination of drive letters and mounted-as-folders. When I try to run a command to remove files (delete incomplete/invalid plots) I get errors using "\\\\" within the filenames, like so:
` C:\Plots\ChiaPlots_Int_I_2)
    > plot-k32-2021-08-11-04-38-1a46b964c8b4b68a03e8c698ea5855d62ae03f319c971fa06bd6ca6712e8b439.plot  found in (C:\Plots\ChiaPlots_Int_I_1 , C:\Plots\ChiaPlots_Int_I_2)
? Do you want to DELETE DUPLICATE files?  Yes
    * Deleting [C:\Plots\ChiaPlots_Ext_A_0\plot-k32-2021-08-18-01-44-7407920ba2a8c3e55797f150676a0321cba4f4ea5a3924d311d608f5d8d310ee.plot]
    * Deleting [D:\\plot-k32-2021-08-21-11-28-4eb49a17ce43aa848a8708f55366f70b06ee5a374dd332df72f5ef9e747dcd5f.plot]
    * Deleting [D:\\plot-k32-2021-08-10-05-20-da44ad584ca63ad272018d7b94b056c0e9c59f7c396f54382c2bb4e429083fe2.plot]
Traceback (most recent call last):
  File "C:\Users\chia\Manage-Chia-Farm\manage-chia-farm.py", line 167, in <module>
    find_duplicate_plots ( )
  File "C:\Users\chia\Manage-Chia-Farm\helpers.py", line 208, in find_duplicate_plots
    os.remove ( file_to_delete )
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'D:\\\\plot-k32-2021-08-10-05-20-da44ad584ca63ad272018d7b94b056c0e9c59f7c396f54382c2bb4e429083fe2.plot'`

And then it crashes back to my cmd prompt.

**Comment by aelfakih** [comment]
Thanks for the report. I will look into it. It seems that the it could not find the file in question.  
To help me understand a possible scenario, are you plotting or moving files around in the background while MCF is scanning?

**Comment by aelfakih** [comment]
Found and closed the offending code. Thank you for the report. Hope it has been helpful in managing your Chia farm! Enjoy -- Adonis

**Comment by JerkyChew899** [comment]
Great, thanks!

**Comment by aelfakih** [comment]
Hi! I open a discussion section, please feel free to share your ideas and questions there.
