### ISSUE TITLE
Script erroneously reports available space of root drive when moving into mounted subfolders

### ISSUE THREAD

**Issue by JerkyChew899** [aelfakih/Manage-Chia-Farm#2]
One of my farmers has the following structure:
```
C:\                              - Boot volume
C:\Plots                      - Subfolder
C:\Plots\disk_1           - Separate, mounted disk 1
C:\Plots\disk_2           - Separate, mounted disk 2
etc...
```

When I run the script and choose import into farm, I choose a mapped drive. MCF then gives me a list of my disks and says which has the most space. So far so good. However, when I select the destination and the move starts, I get the following alert:

> ? Do you want to import these files?  Yes
>? Which location you wanto to move plots TO?  [C:\Plots\ChiaPlots_Ext_A_0]|  90 NFTs,   0 OGs | Can accommodate 56 k32 plots
>** NOTICE! Some plots will be left behind due to free space available at destination.  (Plots 4545 GiB, Destination: 144 GiB free)
>* You can move the remaining plots to a different destination later by re-running this utility.

MCF seems to be using the free space of C to generate this warning. The file moves do work successfully so it's more of an annoyance than a real show-stopper.

Do you plan on setting up a message board or another way to contact you? I have some usability questions but am unsure how or where to ask.

**Comment by aelfakih** [comment]
Thanks for brining this to my attention. I fixed the issue and will push the fix later today. I will look into a message board to get feedback. I do appreciate your feedback about usability and feel to submit them here for now until I get a boar dup and running.
